[pytest]
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning
    ignore::DeprecationWarning:urllib3.*:
    ignore::urllib3.exceptions.InsecureRequestWarning
markers =
    integration: mark a test as a integration.
    only_win: only Windows tests
env =
    DEBUG=False
    CELERY_EAGER=True
    LOG_SQL=False