[supervisord]
nodaemon=true

[program:gunicorn]
command=gunicorn -k uvicorn.workers.UvicornWorker main_app:app -c /opt/app/gunicorn.conf.py
directory=/opt/app/
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0